jwt:
    secret: "NMr6AkwXsuzNzKIxCH1CIzlqdjp5Cpdj"

server:
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/spring_security
        username: soul
        password: soul
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    security:
        user:
            name: soul
            password: soul
            roles: USER
        application:
            jwt:
                expiration:
                    jwtExpiration: 604800000
                refresh-token:
                    expiration:
                        refreshExpiration: 604800000